### ISSUE TITLE
MIT vs GPL

### ISSUE THREAD

**Issue by User-green** [SCPru/scpwiki#5]
Собсно, тайтлом всё сказано. Почему MIT, а не GPL?

**Comment by jewalky** [comment]
Потому что гпл это вирусное говно и противоречит моему пониманию что абсолютно любой код может использоваться абсолютно как угодно

**Comment by User-green** [comment]
Тонда почему не достояние человечества?

**Comment by jewalky** [comment]
В основном потому, что я ни разу не видел чтобы код лицензировали как Public domain.
